/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com_market;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author godfr
 */
public class pay extends javax.swing.JFrame {

    /**
     * Creates new form pay
     */
    int xMouse;
    int yMouse;
    
    double totalPrice;
    
    public pay() {
        initComponents();
        centerFrame();
        
        Connection conn = new dbConnect().dbcon();
        Statement st;
        ResultSet rs;
        
        try{
            st = (Statement) conn.createStatement();
            String sql = "SELECT price FROM totalPrice";
            rs = st.executeQuery(sql);
            while(rs.next()){
                totalPrice = rs.getDouble("price");
            }
            total_price.setText(totalPrice + "");
        } catch(SQLException ex){
            Logger.getLogger(Auth.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void centerFrame() {

            Dimension windowSize = getSize();
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            Point centerPoint = ge.getCenterPoint();

            int dx = centerPoint.x - windowSize.width / 2;
            int dy = centerPoint.y - windowSize.height / 2;    
            setLocation(dx, dy);
            
            total_paid.requestFocusInWindow();
            panel_refuse.setVisible(false);
            panel_error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_confirm = new javax.swing.JButton();
        total_paid = new javax.swing.JTextField();
        total_price = new javax.swing.JTextField();
        panel_front = new javax.swing.JPanel();
        panel_refuse = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        refuse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel_error = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel1.setText("ราคารวม");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        jLabel2.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel2.setText("จำนวนเงินที่จ่าย");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        btn_confirm.setBackground(new java.awt.Color(92, 184, 92));
        btn_confirm.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        btn_confirm.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com_market_img/icons8_refund_48px.png"))); // NOI18N
        btn_confirm.setText("   ยืนยัน");
        btn_confirm.setBorder(null);
        btn_confirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_confirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_confirmMouseExited(evt);
            }
        });
        jPanel1.add(btn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, 40));

        total_paid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_paid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total_paid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(total_paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 140, 40));

        total_price.setBackground(new java.awt.Color(7, 23, 35));
        total_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_price.setForeground(new java.awt.Color(255, 255, 255));
        total_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total_price.setText("   ");
        total_price.setBorder(null);
        jPanel1.add(total_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, 40));

        panel_front.setBackground(new java.awt.Color(7, 23, 35));
        panel_front.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(panel_front, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 150));

        panel_refuse.setBackground(new java.awt.Color(7, 23, 35));
        panel_refuse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("เงินทอน");
        panel_refuse.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        refuse.setBackground(new java.awt.Color(7, 23, 35));
        refuse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refuse.setForeground(new java.awt.Color(255, 255, 255));
        refuse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel_refuse.add(refuse, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 130, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com_market_img/icons8_checkmark_64px.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panel_refuse.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("พิมพ์ใบเสร็จ");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        panel_refuse.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 95, 150, 40));

        jPanel1.add(panel_refuse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 150));

        panel_error.setBackground(new java.awt.Color(7, 23, 35));
        panel_error.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("จำนวนเงินไม่เพียงพอ");
        panel_error.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com_market_img/icons8_close_window_48px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panel_error.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jPanel1.add(panel_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com_market_img/cross_dashboard.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com_market_img/minimize_dashboard.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmMouseClicked
        panel_refuse.setVisible(true);
        panel_error.setVisible(true);
        panel_front.setVisible(false);
        
        if(Integer.parseInt(total_paid.getText()) - totalPrice < 0){
            panel_refuse.setVisible(false);
        } else refuse.setText((Integer.parseInt(total_paid.getText()) - totalPrice) + "");
    }//GEN-LAST:event_btn_confirmMouseClicked

    private void btn_confirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmMouseEntered
        btn_confirm.setBackground(new Color(0, 166, 90));
    }//GEN-LAST:event_btn_confirmMouseEntered

    private void btn_confirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmMouseExited
        btn_confirm.setBackground(new Color(92,184,92));
    }//GEN-LAST:event_btn_confirmMouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new receipt().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_error;
    private javax.swing.JPanel panel_front;
    private javax.swing.JPanel panel_refuse;
    private javax.swing.JTextField refuse;
    private javax.swing.JTextField total_paid;
    private javax.swing.JTextField total_price;
    // End of variables declaration//GEN-END:variables
}
